In [1]:
from pandas import DataFrame
import numpy as np
import time
import math
import sqlite3
import datetime

In [5]:
constantsDF = wholeDatabaseToPandas("cv4DatabaseSarMdac.db", "cv4")
constantsDF

,timestamp,runNumber,serialNumber,ASIC_ID,channel,MDACCorrectionCode0_RAW,MDACCorrectionCode1_RAW,MDACCorrectionCode2_RAW,MDACCorrectionCode3_RAW,MDACCorrectionCode4_RAW,...,SARCorrectionCode11,SARCorrectionCode12,SARCorrectionCode13,SARCorrectionCode14,SARCorrectionCode15,SARCorrectionCode16,SARCorrectionCode17,SARCorrectionCode18,SARCorrectionCode19,SARCorrectionCode20
0,3/9/2022 19:26:30,1,169153,0,1,242.031937,4339.556000,4338.930000,4338.739438,4340.109000,...,245,490,853,496,996,1493,2486,3976,7946,13906
1,3/9/2022 19:30:31,2,169153,0,2,271.260500,4367.445000,4368.529188,4368.197187,4370.077125,...,243,487,847,496,997,1493,2487,3977,7945,13906
2,3/9/2022 19:49:50,3,169153,0,3,300.421250,4396.506687,4398.141312,4397.221438,4398.747000,...,246,493,859,497,997,1493,2488,3977,7943,13906
3,3/9/2022 19:53:36,4,169153,0,4,253.968938,4351.209625,4351.293187,4351.265000,4350.964187,...,245,493,859,497,997,1492,2486,3975,7944,13906
4,3/9/2022 19:57:55,5,169153,0,5,261.702750,4359.294875,4358.778188,4357.324062,4359.586312,...,300,602,1049,497,997,1495,2487,3976,7944,13906
5,3/9/2022 20:1:49,6,169153,0,6,251.506937,4349.101500,4347.925938,4344.985375,4347.555062,...,246,491,856,497,996,1493,2486,3977,7945,13906
6,3/9/2022 20:5:45,7,169153,0,7,248.533187,4347.543000,4347.224187,4347.006562,4348.572813,...,250,502,874,497,997,1493,2487,3977,7947,13906
7,3/9/2022 20:10:2,8,169153,0,8,226.975000,4324.271937,4322.262813,4322.129250,4324.652812,...,248,496,864,496,995,1493,2486,3973,7946,13906
8,3/9/2022 20:13:42,9,169153,0,1,241.969625,4339.278000,4338.596562,4338.543500,4339.790937,...,245,489,853,496,996,1493,2487,3976,7945,13906
9,3/9/2022 20:17:22,10,169153,0,2,271.114063,4367.463938,4368.573000,4368.664375,4370.372375,...,242,486,846,497,997,1494,2486,3977,7944,13906
10,3/9/2022 20:21:23,11,169153,0,3,299.828313,4397.041938,4397.850375,4397.411750,4399.034688,...,247,492,859,497,997,1493,2488,3977,7944,13906
11,3/9/2022 20:26:36,12,169153,0,4,253.844125,4351.541625,4350.781375,4350.295687,4351.051438,...,248,498,867,496,996,1492,2487,3976,7944,13906
12,3/9/2022 20:30:17,13,169153,0,5,262.092875,4359.293625,4358.232438,4357.568875,4359.473625,...,300,601,1048,497,997,1494,2487,3976,7944,13906
13,3/9/2022 20:33:59,14,169153,0,6,251.219938,4349.040250,4348.012437,4345.162625,4347.380312,...,244,489,853,497,996,1493,2486,3977,7946,13906
14,3/9/2022 20:42:16,15,169153,0,7,248.205875,4347.514375,4347.312937,4347.555937,4348.696875,...,249,501,873,497,996,1493,2487,3977,7948,13906
15,3/9/2022 20:46:6,16,169153,0,8,226.645687,4324.067875,4321.741812,4321.825063,4324.835000,...,249,500,870,496,995,1493,2487,3973,7947,13906
16,3/9/2022 20:49:49,17,169153,0,1,242.032000,4339.488125,4338.864500,4339.112625,4340.635937,...,245,492,857,496,996,1492,2486,3975,7943,13906
17,3/9/2022 20:57:33,18,169153,0,2,270.594563,4367.026313,4368.553562,4367.749938,4370.146062,...,243,487,848,497,997,1493,2487,3976,7944,13906
18,3/9/2022 21:1:19,19,169153,0,3,300.152812,4396.326875,4397.992750,4397.783125,4399.205750,...,249,496,865,496,997,1493,2488,3977,7944,13906
19,3/9/2022 21:5:27,20,169153,0,4,253.760125,4351.734812,4351.089937,4350.566875,4350.404625,...,246,493,860,497,996,1492,2486,3975,7944,13906
20,3/9/2022 21:9:38,21,169153,0,5,262.089125,4359.580750,4358.800062,4357.601000,4359.980125,...,303,607,1059,497,996,1495,2487,3977,7945,13906
21,3/9/2022 21:13:17,22,169153,0,6,250.758437,4348.702312,4347.544437,4345.355312,4346.458188,...,245,490,853,497,996,1493,2486,3977,7945,13906
22,3/9/2022 21:18:11,23,169153,0,7,248.188312,4346.862562,4347.564313,4347.020125,4348.232000,...,249,500,873,497,997,1493,2487,3977,7948,13906
23,3/9/2022 21:21:52,24,169153,0,8,226.403812,4324.040125,4322.479250,4321.811125,4324.368250,...,248,497,865,496,995,1493,2487,3974,7948,13906
24,3/9/2022 21:26:3,25,169153,0,1,241.810875,4338.975062,4338.640188,4339.072375,4340.315937,...,245,490,855,496,996,1492,2487,3975,7945,13906
25,3/9/2022 21:29:55,26,169153,0,2,270.726812,4367.193000,4369.064000,4368.534875,4369.602000,...,242,486,846,497,997,1493,2486,3976,7943,13906
26,3/9/2022 21:34:0,27,169153,0,3,300.359312,4396.878062,4398.048187,4397.327812,4398.851625,...,246,493,860,496,997,1493,2488,3977,7944,13906
27,3/9/2022 21:38:12,28,169153,0,4,253.668500,4350.971625,4350.949125,4349.744062,4350.909813,...,246,494,860,497,996,1492,2486,3976,7944,13906
28,3/9/2022 21:42:19,29,169153,0,5,261.766000,4359.328938,4358.593750,4357.785062,4359.220750,...,306,614,1070,497,997,1495,2487,3976,7944,13906
29,3/9/2022 21:46:12,30,169153,0,6,250.794875,4348.710125,4347.385563,4345.054500,4346.757875,...,246,493,859,497,996,1493,2486,3977,7945,13906
30,3/9/2022 21:49:57,31,169153,0,7,248.425250,4348.254000,4347.676937,4347.355687,4349.032438,...,251,503,878,497,997,1492,2487,3977,7948,13906
31,3/9/2022 21:53:39,32,169153,0,8,226.374812,4324.641875,4322.785500,4321.815687,4325.111750,...,249,499,868,495,995,1492,2487,3973,7948,13906

In [7]:
constantsDF.loc[constantsDF['channel'] == 2]

,timestamp,runNumber,serialNumber,ASIC_ID,channel,MDACCorrectionCode0_RAW,MDACCorrectionCode1_RAW,MDACCorrectionCode2_RAW,MDACCorrectionCode3_RAW,MDACCorrectionCode4_RAW,...,SARCorrectionCode11,SARCorrectionCode12,SARCorrectionCode13,SARCorrectionCode14,SARCorrectionCode15,SARCorrectionCode16,SARCorrectionCode17,SARCorrectionCode18,SARCorrectionCode19,SARCorrectionCode20
1,3/9/2022 19:30:31,2,169153,0,2,271.260500,4367.445000,4368.529188,4368.197187,4370.077125,...,243,487,847,496,997,1493,2487,3977,7945,13906
9,3/9/2022 20:17:22,10,169153,0,2,271.114063,4367.463938,4368.573000,4368.664375,4370.372375,...,242,486,846,497,997,1494,2486,3977,7944,13906
17,3/9/2022 20:57:33,18,169153,0,2,270.594563,4367.026313,4368.553562,4367.749938,4370.146062,...,243,487,848,497,997,1493,2487,3976,7944,13906
25,3/9/2022 21:29:55,26,169153,0,2,270.726812,4367.193000,4369.064000,4368.534875,4369.602000,...,242,486,846,497,997,1493,2486,3976,7943,13906

In [14]:
#Keep Relevant Functions Here

def wholeDatabaseToPandas(database = "cv4DatabaseSarMdac.db", table = "cv4"):
    conn = sqlite3.connect(database)
    c = conn.cursor()
    df = DataFrame(c.execute(f"SELECT * FROM {table}").fetchall())

    column_names = []
    for column in c.execute(f"pragma table_info({table});").fetchall():
        column_names.append(column[1])
    df.columns = column_names

    conn.commit()
    conn.close()

    return df

def getSpecificChannelDF(chNum, database = "cv4DatabaseSarMdac.db", table = "cv4"):
    constantsDF = wholeDatabaseToPandas(database, table)
    channelDF = constantsDF.loc[constantsDF['channel'] == chNum]
    return channelDF

In [17]:
getSpecificChannelDF(8)

,timestamp,runNumber,serialNumber,ASIC_ID,channel,MDACCorrectionCode0_RAW,MDACCorrectionCode1_RAW,MDACCorrectionCode2_RAW,MDACCorrectionCode3_RAW,MDACCorrectionCode4_RAW,...,SARCorrectionCode11,SARCorrectionCode12,SARCorrectionCode13,SARCorrectionCode14,SARCorrectionCode15,SARCorrectionCode16,SARCorrectionCode17,SARCorrectionCode18,SARCorrectionCode19,SARCorrectionCode20
7,3/9/2022 20:10:2,8,169153,0,8,226.975000,4324.271937,4322.262813,4322.129250,4324.652812,...,248,496,864,496,995,1493,2486,3973,7946,13906
15,3/9/2022 20:46:6,16,169153,0,8,226.645687,4324.067875,4321.741812,4321.825063,4324.835000,...,249,500,870,496,995,1493,2487,3973,7947,13906
23,3/9/2022 21:21:52,24,169153,0,8,226.403812,4324.040125,4322.479250,4321.811125,4324.368250,...,248,497,865,496,995,1493,2487,3974,7948,13906
31,3/9/2022 21:53:39,32,169153,0,8,226.374812,4324.641875,4322.785500,4321.815687,4325.111750,...,249,499,868,495,995,1492,2487,3973,7948,13906

In [ ]:
nominalSarVals = {"W_1ST_3584_RAW": 3584, "W_1ST_2048_RAW":2048, "W_1ST_1024_RAW": 1024, "W_1ST_640_RAW": 640, "W_1ST_384_RAW":384, "W_1ST_256_RAW": 256, "W_1ST_128_RAW": 128, "W_2ND_224_RAW": 224, "W_2ND_128_RAW":128, "W_2ND_64_RAW":64, "W_2ND_32_RAW":32, "W_2ND_24_RAW":24, "W_2ND_16_RAW":16, "W_2ND_10_RAW": 10, "W_2ND_6_RAW":6, "W_2ND_4_RAW":4, "W_2ND_2_RAW":2, "W_2ND_1_RAW":1, "W_2ND_0p5_RAW":0.5, "W_2ND_0p25_RAW":0.25}

In [ ]:
def readChannel(chNum, databaseName = "cv4DatabaseSarMdac.db", tableID = "cv4"):